### ISSUE TITLE
Crash when run with TIS-3D

### ISSUE THREAD

**Issue by mrmakeit** [specialattack/SpACoreForge#7]
http://paste.ee/p/aVImZ

Both SpACore and TIS-3D run fine alone, but not at the same time. Appears to be an ASM error. I'm also posting to TIS-3D as well.

**Comment by mrmakeit** [comment]
TIS-3D issue:
https://github.com/MightyPirates/TIS-3D/issues/39

**Comment by heldplayer** [comment]
I think I've fixed the issue. I was still using the ASM4 API rather than ASM5 which should now be available everywhere. Most likely TIS-3D was not compiled for Java 6 so it tried to do an unsupported opcode for that version of the ASM API.

I've put the new version up and it's awaiting approval at http://minecraft.curseforge.com/projects/spacore/files/2274441

Please reply whether the new version has fixed the issue.

**Comment by mrmakeit** [comment]
http://paste.ee/p/X3jX6

SpACore now fails all on it's own.  Not sure if it fixed the TIS-3D issue

**Comment by heldplayer** [comment]
You're using the dev jar. You need the file I linked (2nd download button at the top, not the file at the bottom ;) )

**Comment by heldplayer** [comment]
@mrmakeit Does the problem still exist?

**Comment by mrmakeit** [comment]
My apologies, I've been busy with work for the past couple of days.  I'll
load it up in a few minutes and check.

On Wed, Jan 13, 2016, 04:38 heldplayer <notifications@github.com> wrote:

> @mrmakeit <https://github.com/mrmakeit> Does the problem still exist?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/specialattack/SpACoreForge/issues/7#issuecomment-171250369>
> .
>
-- 

-------------------------------------------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by mrmakeit** [comment]
Looks like that fixed it.  Closing.
